swiftmailer:
    url: '%env(MAILER_URL)%'
    #spool: { type: 'memory' }
    #transport: smtp
    sender_address: info@factoriastartup.com
    transport:  smtp
    #encryption: tls
    #auth_mode:  login
    #host:       smtp.hostinger.es:587
    #username:  info@factoriastartup.com
    #password:  iliuta123
    username:  liviuromania@gmail.com
    password:  Zorilor098.
