index:
    path: /
    controller: App\Controller\DefaultController::index 
   
admin-projects:
    path: /admin_projects
    controller: App\Controller\AdminProjectsController::index
admin-projects-project:
    path: /admin_projects/project/{id}
    controller: App\Controller\AdminProjectsController::project   
admin-coworker:
    path: /admin_projects/admin_coworker
    controller: App\Controller\AdminProjectsController::index_coworker 

user:
    path: /user
    controller: App\Controller\UserController::index_vista    

add-profile:
    path: /user/add-profile
    controller: App\Controller\ProfileController::addProfileUser
    options:
        expose: true

edit-profile:
    path: /user/edit-profile/{id}
    controller: App\Controller\ProfileController::editProfileUser
    options:
        expose: true

update-profile:
    path: /user/update-update/{id}
    controller: App\Controller\ProfileController::editProfilUserUpdate
    methods:  [GET,POST]
    options:
        expose: true

delete-profile:
    path: /user/delete-profile/{id}
    controller: App\Controller\ProfileController::deleteUserProfile
    options:
        expose: true

add-project:
    path: /user/add-project/{id}
    controller: App\Controller\UserProjectController::addProject

delete-project:
    path: /user/delete-project/{id}
    controller: App\Controller\UserController::deleteProject
    methods:  [GET,POST]
    options:
        expose: true
        
delete-profile-Interest:
    path: /user/delete-profile-interest/{id}
    controller: App\Controller\UserController::deleteProfileInterest
    methods:  [GET,POST]
    options:
        expose: true
delete-project-interest:
    path: /user/delete-project-interest/{id}
    controller: App\Controller\UserController::deleteProjectInterest
    methods:  [GET,POST]
    options:
        expose: true        

add-Profile-to-project:   
    path: /user/add-project/profile/{id}
    controller: App\Controller\UserProjectController::addProfileToProject
    methods:  [GET,POST]
    options:
        expose: true 
        
delete-profile-project:        
    path: /user/delete-Profile-project/profile/{id}
    controller: App\Controller\UserProjectController::deleteProfileProject
    methods:  [GET,POST]
    options:
        expose: true 
    
project-needs:
    path: /user/add-project/project-needs/{id}
    controller: App\Controller\UserProjectController::ProjectNeeds
    methods:  [GET,POST]

delete-profile-needs:
    path: /user/delete_Profile_needs/step_3/{id}
    controller: App\Controller\UserProjectController::deleteProfileNeeds
    methods:  [GET,POST]
    options:
        expose: true

personal-info:
    path: /user/personal-info
    controller: App\Controller\UserController::personalInfo 
professional-info:
    path: /user/professional-info
    controller: App\Controller\UserController::professionalInfo
projects-info:
    path: /user/projects-info
    controller: App\Controller\UserController::projectsInfo  
proposals-info:
    path: /user/proposals-info
    controller: App\Controller\UserController::proposalsInfo  

interest-select-profile:
    path: /project/{id}/interest-profile-select
    controller: App\Controller\ProjectController::interestSelectProfile
    methods:  [GET,POST]
    options:
        expose: true

projects:
    path: /projects
    controller: App\Controller\ProjectController::indexProject
projects-filter:
    path: /projects/{sector}/{km}/{lat}/{long}
    controller: App\Controller\ProjectController::indexProjectFilter
    methods:  [GET,POST]
    options:
        expose: true              
project:
    path: /projects/{id}
    controller: App\Controller\ProjectController::project

profiles:
    path: /profiles
    controller: App\Controller\ProfileUserController::indexProfile
profile:
    path: /profiles/{id}
    controller: App\Controller\ProfileUserController::profile 
profiles-filter:
    path: /profiles/{profiles}/{km}/{lat}/{long}
    controller: App\Controller\ProfileUserController::indexProfileFilter
    methods:  [GET,POST]
    options:
        expose: true   

match-project:
    path: /match/{userid}/{projectid}
    controller: App\Controller\MatchProjectController::getMatch
    options:
        expose: true

 #Messages
list-messages:
    path: /user/messages
    controller: App\Controller\MessageController::listMessages

message:
    path: /user/messages/{id}
    controller: App\Controller\MessageController::message 
    

#Notes
list-notes:
    path: /user/notes
    controller: App\Controller\NotesController::listNotes

note:
    path: /user/notes/{id}/{type_interest}
    controller: App\Controller\NotesController::note 


#NOT IN USE    
herramientas:
    path: /herramientas
    controller: App\Controller\HerramientasController::index 
noticias:
    path: /noticias
    controller: App\Controller\NoticiasController::index  
noticia:
    path: /noticias/id_noticia
    controller: App\Controller\NoticiasController::noticias

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
