index:
    path: /
    controller: App\Controller\DefaultController::index 
vista_usuario:
    path: /vista_usuario
    controller: App\Controller\VistaUsuarioController::index_vista    
equipo:
    path: /profiles
    controller: App\Controller\ProfileUserController::indexProfile 
add_profile:
    path: /profiles/añadir
    controller: App\Controller\ProfileUserController::addProfile     
detalle_profile:
    path: /profiles/{id}
    controller: App\Controller\ProfileUserController::profile 
editar_profile:
    path: /profiles/modificar/{id}
    controller: App\Controller\ProfileUserController::editProfile  
eliminar_profile:
    path: /profiles/eliminar/{id}
    controller: App\Controller\ProfileUserController::delete
   


proyectos:
    path: /proyectos
    controller: App\Controller\ProjectController::indexProject
add_project:
    path: /proyectos/añadir
    controller: App\Controller\ProjectController::add              
detalle_proyecto:
    path: /proyectos/{id}
    controller: App\Controller\ProjectController::project
editar_proyecto:
    path: /proyectos/modificar/{id}
    controller: App\Controller\ProjectController::edit  
eliminar_proyecto:
    path: /proyectos/eliminar/{id}
    controller: App\Controller\ProjectController::delete      

        


añadir_proyecto:
    path: /vista_usuario/añadir_proyecto
    controller: App\Controller\VistaUsuarioController::añadir_proyecto 
datos_personales:
    path: /vista_usuario/datos_personales
    controller: App\Controller\VistaUsuarioController::datos_personales 
datos_profesionales:
    path: /vista_usuario/datos_profesionales
    controller: App\Controller\VistaUsuarioController::datos_profesionales
datos_proyectos:
    path: /vista_usuario/datos_proyectos
    controller: App\Controller\VistaUsuarioController::datos_proyectos
 
datos_propuestas:
    path: /vista_usuario/datos_propuestas
    controller: App\Controller\VistaUsuarioController::datos_propuestas  
datos_cuenta:
    path: /vista_usuario/datos_cuenta
    controller: App\Controller\VistaUsuarioController::datos_cuenta


herramientas:
    path: /herramientas
    controller: App\Controller\HerramientasController::index 
foro:
    path: /foro
    controller: App\Controller\ForoController::index 

    
posts:
    path: /posts
    controller: App\Controller\PostsController::indexAction        
add_posts:
    path: /posts/add
    controller: App\Controller\PostsController::addAction
delete_posts:
    path: /posts/delete/{id}
    controller: App\Controller\PostsController::deleteAction
edit_posts:
    path: /posts/edit/{id}
    controller: App\Controller\PostsController::editAction
posts_details:
    path: /posts/detail/{id}
    controller: App\Controller\PostsController::detailAction     