index:
    path: /
    controller: App\Controller\DefaultController::index
login:
    path: /login
    controller: App\Controller\RegistrationController::loginAction
logout:
    path: /logout      
proyectos:
    path: /proyectos
    controller: App\Controller\BuscarController::proyectos   
equipo:
    path: /equipo
    controller: App\Controller\BuscarController::equipo       
detalle_proyecto:
    path: /detalleProyecto
    controller: App\Controller\DetalleController::proyecto 
detalle_usuario:
    path: /detalleUsuario
    controller: App\Controller\DetalleController::usuario     
vista_usuario:
    path: /vista_usuario
    controller: App\Controller\VistaUsuarioController::index_vista
datos_personales:
    path: /vista_usuario/datos_personales
    controller: App\Controller\VistaUsuarioController::datos_personales 
datos_profesionales:
    path: /vista_usuario/datos_profesionales
    controller: App\Controller\VistaUsuarioController::datos_profesionales
datos_proyectos:
    path: /vista_usuario/datos_proyectos
    controller: App\Controller\VistaUsuarioController::datos_proyectos
añadir_proyecto:
    path: /vista_usuario/añadir_proyecto
    controller: App\Controller\VistaUsuarioController::añadir_proyecto  
datos_propuestas:
    path: /vista_usuario/datos_propuestas
    controller: App\Controller\VistaUsuarioController::datos_propuestas  
datos_cuenta:
    path: /vista_usuario/datos_cuenta
    controller: App\Controller\VistaUsuarioController::datos_cuenta
herramientas:
    path: /herramientas
    controller: App\Controller\HerramientasController::index 
foro:
    path: /foro
    controller: App\Controller\ForoController::index 
noticias:
    path: /noticias
    controller: App\Controller\NoticiasController::index  
noticia:
    path: /noticias/id_noticia
    controller: App\Controller\NoticiasController::noticias                             