index:
    path: /
    controller: App\Controller\DefaultController::index
login:
    path: /login
    controller: App\Controller\RegistrationController::loginAction
logout:
    path: /logout      
proyectos_equipos:
    path: /proyectos_equipos
    controller: App\Controller\ProyectosController::index    
detalle_proyecto:
    path: /detalle_proyecto
    controller: App\Controller\DetalleProyectoController::index  
vista_usuario:
    path: /vista_usuario
    controller: App\Controller\VistaUsuarioController::index 