index:
    path: /
    controller: App\Controller\DefaultController::index 
vista_usuario:
    path: /vista_usuario
    controller: App\Controller\UserController::index_vista    

equipo:
    path: /profiles
    controller: App\Controller\ProfileUserController::indexProfile 

addProfil:
    path: /addProfil
    controller: App\Controller\SingelProfile::addProfileUser
    options:
        expose: true

editProfileUser:
    path: /addProfileUser/{id}
    controller: App\Controller\SingelProfile::editProfileUser
    options:
        expose: true

editProfilUserUpdate:
    path: /editProfilUserUpdate/{id}
    controller: App\Controller\SingelProfile::editProfilUserUpdate
    methods:  [GET,POST]
    options:
        expose: true

deleteUserProfile:
    path: /deleteUserProfile/{id}
    controller: App\Controller\SingelProfile::deleteUserProfile
    options:
        expose: true
        
detalle_profile:
    path: /profiles/{id}
    controller: App\Controller\ProfileUserController::profile 

editar_profile:
    path: /profiles/modificar/{id}
    controller: App\Controller\ProfileUserController::editProfile  
eliminar_profile:
    path: /profiles/eliminar/{id}
    controller: App\Controller\ProfileUserController::delete
   


proyectos:
    path: /proyectos
    controller: App\Controller\ProjectController::indexProject
add_project:
    path: /proyectos/add
    controller: App\Controller\ProjectController::add              
detalle_proyecto:
    path: /proyectos/{id}
    controller: App\Controller\ProjectController::project
editar_proyecto:
    path: /proyectos/modificar/{id}
    controller: App\Controller\ProjectController::edit  
eliminar_proyecto:
    path: /proyectos/eliminar/{id}
    controller: App\Controller\ProjectController::delete 
addPerfilToProyect:   
    path: /addPerfilToProyect/{id}
    controller: App\Controller\UserProjectController::addPerfilToProyect
    methods:  [GET,POST]
    options:
        expose: true
        


add_proyecto:
    path: /vista_usuario/add_proyecto
    controller: App\Controller\UserController::add_proyecto 
datos_personales:
    path: /datos_personales
    controller: App\Controller\UserController::datos_personales 
datos_profesionales:
    path: /datos_profesionales
    controller: App\Controller\UserController::datosProfesionales
datos_proyectos:
    path: /vista_usuario/datos_proyectos
    controller: App\Controller\UserController::datos_proyectos
 
datos_propuestas:
    path: /vista_usuario/datos_propuestas
    controller: App\Controller\UserController::datos_propuestas  
datos_cuenta:
    path: /vista_usuario/datos_cuenta
    controller: App\Controller\UserController::datos_cuenta


herramientas:
    path: /herramientas
    controller: App\Controller\HerramientasController::index 
foro:
    path: /foro
    controller: App\Controller\ForoController::index 
noticias:
    path: /noticias
    controller: App\Controller\NoticiasController::index  
noticia:
    path: /noticias/id_noticia
    controller: App\Controller\NoticiasController::noticias                             