index:
    path: /
    controller: App\Controller\DefaultController::index
login:
    path: /login
    controller: App\Controller\RegistrationController::loginAction
logout:
    path: /logout    
proyectos_equipos:
    path: /proyectos_equipos
    controller: App\Controller\ProyectosController::index    
